name: Go

on:
  workflow_dispatch:
  push:
    branches: [ 'development' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  
  tests-and-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        go_version: ['1.17', '1.18', '>=1.18']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go_version }}

    - name: Build database
      run: docker-compose build

    - name: Create database
      run: docker-compose up -d

    - name: build
      run: go build main.go
            
    - name: OpenCommit — improve commits with AI 🧙
      uses: di-sukharev/opencommit@github-action-v1.0.2
            
